version: '3'

services:
  postgresql:
    container_name: PostgreSQL-sellit
    build:
      context: postgresql
      dockerfile: Dockerfile
    ports:
      - 5450:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

  spring:
    container_name: Backend_sellit
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/"${POSTGRES_DB}"
    ports:
      - 8080:8080
#    networks:
#      - sellit_network
    depends_on:
      - postgresql

  reactjs:
    container_name: React_sellit
    build:
      context: frontend/react-app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - spring
    stdin_open: true

#networks:
#  sellit_network:
#    driver: bridge

volumes:
  pg-data: